### ISSUE TITLE
main file instead of partial?

### ISSUE THREAD

**Issue by tomekk-hnm** [kiennp/web-assets-compiler#1]
Is it possible to compile only "main" files, while saving a partial file or watching folder and subfolders? Did i miss something?

**Comment by kiennp** [comment]
Can you explain your case with folder structure?

**Comment by tomekk-hnm** [comment]
Hi there, thank you for your quick reply.

Of course, the folder structure is as follows:
/root-scss
/root-scss/sub-scss-folder

/root-scss contains:
main.scss
main2.scss
_another-partial.scss

/root-scss/sub-scss-folder contains:
_buttons.scss
_nav.scss
_partial.scss
...

Now I want to save a partial file (e.g. _buttons.scss), so that it triggers the "main" files, i.e. all files without the "_" at the beginning in the root folder, in this case main.scss and main2.scss but not _another-partial or partials in subfolder.

Does this make it clearer to you?

**Comment by kiennp** [comment]
You want to compile `main.scss` automatically when save `_another-partial.scss` because `main.css` is including `_another-partial.scss`.
Is that right?
Now you can exclude partial files and sub folders but files that using or including excluded files won't be auto-compile when you save excluded files.
You must run command Compile all to re-compile all files when you save excluded files.
I'll try to support auto-compile for this case.
